"""
Generate emergency health summary PDF using ReportLab.
This PDF is printable / shareable offline — critical for ICU/ER scenarios.
"""
import io
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors


def generate_emergency_pdf(summary: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.5 * inch)
    styles = getSampleStyleSheet()

    red_title = ParagraphStyle(
        "RedTitle", parent=styles["Heading1"], textColor=colors.red, fontSize=20
    )
    section_style = ParagraphStyle(
        "Section", parent=styles["Heading2"], textColor=colors.darkblue, fontSize=13
    )

    story = [
        Paragraph("🚨 EMERGENCY HEALTH SUMMARY", red_title),
        Paragraph("VitaClan – Vital Records for Your Clan", styles["Normal"]),
        Spacer(1, 0.2 * inch),
        Paragraph(f"<b>Name:</b> {summary.get('name', 'Unknown')}", styles["Normal"]),
        Paragraph(f"<b>Phone:</b> {summary.get('phone', '')}", styles["Normal"]),
        Paragraph(f"<b>Blood Group:</b> {summary.get('blood_group', 'Unknown')}", styles["Normal"]),
        Spacer(1, 0.15 * inch),
    ]

    if summary.get("allergies"):
        story.append(Paragraph("⚠️ ALLERGIES", section_style))
        for allergy in summary["allergies"]:
            story.append(Paragraph(f"• {allergy}", styles["Normal"]))
        story.append(Spacer(1, 0.1 * inch))

    if summary.get("conditions"):
        story.append(Paragraph("🏥 MEDICAL CONDITIONS", section_style))
        for condition in summary["conditions"]:
            story.append(Paragraph(f"• {condition}", styles["Normal"]))
        story.append(Spacer(1, 0.1 * inch))

    if summary.get("active_medications"):
        story.append(Paragraph("💊 CURRENT MEDICATIONS", section_style))
        data = [["Medicine", "Dosage", "Frequency"]]
        for m in summary["active_medications"]:
            data.append([m.get("name", ""), m.get("dosage", ""), m.get("frequency", "")])

        table = Table(data, colWidths=[2.5 * inch, 1.5 * inch, 2 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.lightblue]),
        ]))
        story.append(table)
        story.append(Spacer(1, 0.15 * inch))

    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph(
        "⚠️ This document is for emergency reference only. Always consult a qualified healthcare professional.",
        ParagraphStyle("Disclaimer", parent=styles["Normal"], textColor=colors.grey, fontSize=8),
    ))
    story.append(Paragraph("Generated by VitaClan | Not a medical certificate", styles["Normal"]))

    doc.build(story)
    buffer.seek(0)
    return buffer.read()
